### ISSUE TITLE
module dsconcept missing

### ISSUE THREAD

**Issue by bluetyson** [nasa/concept-tagging-api#5]
sorry, should have put it here 👎 

~/concept-tagging-api/tests$ python context.py
Traceback (most recent call last):
  File "context.py", line 8, in <module>
    import app
  File "/home/ubuntu/concept-tagging-api/service/app.py", line 6, in <module>
    import dsconcept.get_metrics as gm
ModuleNotFoundError: No module named 'dsconcept'

and re: other repo

 fatal: unable to access 'https://developer.nasa.gov/DataSquad/classifier_scripts.git/': Could not resolve host: developer.nasa.gov
ERROR: Command errored out with exit status 128: git clone -q https://developer.nasa.gov/DataSquad/classifier_scripts.git

**Comment by abuonomo** [comment]
Did you try installing the library with this link?
```
pip install git+https://github.com/nasa/concept-tagging-training.git@v1.0.3-open_source_release#egg=dsconcept
```

**Comment by bluetyson** [comment]
Trying to run the app ... no have not tried that one, will give it a shot later today thanks

**Comment by bluetyson** [comment]
That appears to have worked thank you Anthony.  Now just have to wait to be allowed to access it to try it.

**Comment by abuonomo** [comment]
Glad to hear it. Sorry about those misleading links. Would love to hear how it ends up working.

**Comment by bluetyson** [comment]
Speaking of which, do you have a recommended size limit for firing a batch at it, do you think?

**Comment by bluetyson** [comment]
e.g. context being - if this generally working on short abstracts - and start throwing long reports at it to see what comes out - reasonable length for model to handle, that sort of thing.

**Comment by bluetyson** [comment]
Seems at the moment approx 4MB might be a limit (at least at this machine capacity) for a single text payload.

**Comment by abuonomo** [comment]
To optimize speed, my tests (using abstracts) indicated that a batch size of about 700 documents is ideal. More than that gave diminishing returns on speed. If you are working with longer documents, the ideal batch size may be lower. However, I would recommend automatically summarizing the text before sending it to the API, as other tests indicated that this is best for getting the most accurate tags.

**Comment by bluetyson** [comment]
Thanks Anthony, so maybe a megabyte or so in that case?

I am going to do the summarizer as well for the same set and compare.

**Comment by abuonomo** [comment]
I'm not totally sure, but that sounds about right.

**Comment by bluetyson** [comment]
Seems like around 3MB docs with presumably lots of words etc. can run 32GB out of memory and core dump a machine

**Comment by RichardScottOZ** [comment]
Notes on installing this repo: change scm_version to False to get it to in
sudo apt-get install cargo
for rust package manager for example

**Comment by RichardScottOZ** [comment]
and if running local python3 -m spacy download en_core_web_sm
